### ISSUE TITLE
Request for Contribution Guidelines and Project Organization 

### ISSUE THREAD

**Issue by Jupalaja** [animotionjs/animotion#1]
Hello Matija,

I just watch your youtube video, and I'm really excited about the potential of this project. I noticed that there are currently no clear instructions or guidelines for contributors to follow, which makes it a bit challenging to understand how can we best support this project.

Here are a few suggestions that might help streamline the contribution process:

1. **Contribution Guidelines**: A `CONTRIBUTING.md` file which outlines the process of working on an issue, capturing the project's style guidelines, key contact points for communication, etc.

2. **Code of Conduct**: An explicit `CODE_OF_CONDUCT.md` file helps set community standards.

3. **Project Roadmap or Active Tasks**: Highlighting areas of work, whether it's in the 'Issues' tab or a `ROADMAP.md` file, can help contributors direct their efforts effectively.

I'll be happy to assist in creating some of these files if needed. Can you point me in the right direction or provide your thoughts on where you see the most need?

Thank you so much for launching this amazing tool, and I'm looking forward to contributing!

Best,
Jupalaja

**Comment by mattcroat** [comment]
Thank you! 😄

I already added contributing guidelines and a code of conduct. There is no roadmap but I appreciate you for asking to help and any suggestions you might have.
