### ISSUE TITLE
Passing "image" in the Media component doesn't work

### ISSUE THREAD

**Issue by polykhel** [animotionjs/animotion#10]
The Media component expects the type to be one of 'video' | 'image' | 'iframe'.

Passing "image" type to the Media component creates an HTML element _image_, which doesn't exist.

Type should be _img_ or retain the _image_ parameter but convert it to "img" inside Media.svelte.

**Comment by mattcroat** [comment]
![surprised](https://github.com/animotionjs/animotion/assets/38083522/ed8a59ec-e4b8-4fbc-9fc5-d863bc7e5a5f)

Thank you! 😄 I fixed it.

**Comment by mr13tech** [comment]
There is still minor issue. The docs says to pass `img` as type, and it does work with that. But inside `Media` component type still has `image` - hence linter errpor - bad dev exp.

suggest: change `image` -> `img` in generated `Media` component

**Comment by mattcroat** [comment]
@mr13tech I can't seem to find any reference to that.
