### ISSUE TITLE
Create documentation on how to install and integrate on an existing project

### ISSUE THREAD

**Issue by ChrisPoul** [animotionjs/animotion#11]
I am trying to use this library on a svelte project I have, I tried looking through the docs but it doesn't say anything about how to install it and set it up on an existing project. I think this is necessary for adoption and for realistic use cases, since a lot of people will want to use it on existing projects.

**Comment by mattcroat** [comment]
You can't because there is no Animotion package you can import and use because it would require a lot of setup.
