### ISSUE TITLE
Total slide numbers not displaying on pdf

### ISSUE THREAD

**Issue by MarvinZein** [animotionjs/animotion#19]
Hello,

in the config.ts in the Reveal.Options object, when I set the following:

`
slideNumber: 'c/t',
showSlideNumber: 'all'
`

It only displays the total number of slides in the normal view, but not on the printed pdf when I go to http://localhost:5173/?print-pdf and print to pdf

**Comment by mattcroat** [comment]
I never used this feature but it looks right to me. The [PDF Export](https://revealjs.com/pdf-export/) section of the Reveal docs mention it only works in Chrome browsers.

![image](https://github.com/animotionjs/animotion/assets/38083522/1afdd7d5-312d-442c-b709-f911610a1a09)

**Comment by marvwebdev** [comment]
Yes, that is also what I get. It only shows the current slide. But I want it to show the current silde / total number of slides (like 1/3 , 2/3, 3/3). That it only does in the normal view, but not in the "pdf view"

**Comment by marvwebdev** [comment]
That is what the 'c/t' is for

**Comment by mattcroat** [comment]
@marvwebdev It might be because I haven't included the print styles but I'm going to have a look.

**Comment by mattcroat** [comment]
@marvwebdev I tried it and it didn't make a difference but I found https://github.com/hakimel/reveal.js/issues/2166 and I think you can't control the number format when printing, so I don't know.
