### ISSUE TITLE
Pipe character in code block does nothing

### ISSUE THREAD

**Issue by monstajoe2002** [animotionjs/animotion#20]
According to the docs, `lines="1-2|4"` first highlights lines 1 to 2 then highlight line 4. However, in my case, it highlights the first to lines.
Also, I can't seem to make the code auto shrink even after applying `flex-wrap`. 
![image](https://github.com/animotionjs/animotion/assets/95737443/8edd08a0-cd0f-4029-82b8-80152431e35f)

**Comment by mattcroat** [comment]
Please include a reproduction.
