### ISSUE TITLE
Prefetch api data at build time

### ISSUE THREAD

**Issue by dldx** [animotionjs/animotion#25]
First of all, thanks for this amazing library. It is very nice to use!

Not sure if this is the right place to ask this question but I'm constructing charts within `slides.svelte` using data fetched from an external API. I would like the data to be cached within at build time if possible, like with sveltekit prerendering. Any thoughts on how to achieve it?

Cheers,
Durand

**Comment by mattcroat** [comment]
No idea but in the next Animotion update I'm going to use the SvelteKit template to make it easier.

**Comment by dldx** [comment]
Ah, sounds great!
