### ISSUE TITLE
Changing Slide/Transition from code

### ISSUE THREAD

**Issue by flymedllva** [animotionjs/animotion#27]
In all the examples, you make a new Slide and place a Transition in it. It turns out that when I open the slide I see a blank page, although I would like to see the result of the first animation.
This gave me the idea to switch the Transition when the slide is turned on, but I haven't found how to do it.

**Comment by mattcroat** [comment]
You can pass the `visible` attribute from the [docs example](https://animotion.pages.dev/docs/transitions) if you only want to animate the element in the future:

```svelte
<Slide>
  <Transition visible>
    Visible
  </Transition>
</Slide>
```
