### ISSUE TITLE
Need more examples 

### ISSUE THREAD

**Issue by flymedllva** [animotionjs/animotion#29]
Need more examples from where you can copy code and quickly sketch out a presentation

Now it is suggested to recall tailwind/css, it would be cool to have pieces of code resembling templates from PowerPoint
As an example:
- text header on the top left, and the main text content below that
- slide divided into 2 parts - text and photo (group of photos)

**Comment by mattcroat** [comment]
That's a great idea and I would love to expand the default example to include these suggestions.
