### ISSUE TITLE
npm create @animotion just runs empty npm init

### ISSUE THREAD

**Issue by gertminov** [animotionjs/animotion#3]
Hi great project!

I followed the getting started guide on [the website](https://animotionjs.vercel.app/docs/getting-started) and ran into the problem, that if i run `npm create @animotion` i just get prompted with the standart `npm init` and end up with an empty `package.json`

using:
```
npx  @animotion/create
```

worked though.

I dont know wheter thats just a bug with my setup, but maybe giving an alternative in the docs might help.

**Comment by krayfaus** [comment]
Sorry to bump this, but please update the README as well.

**Comment by mattcroat** [comment]
> Sorry to bump this, but please update the README as well.

Done! 😄

**Comment by mattcroat** [comment]
@krayfaus Thank you! 😄
