### ISSUE TITLE
Notes glitching

### ISSUE THREAD

**Issue by ImBIOS** [animotionjs/animotion#33]
![image](https://github.com/user-attachments/assets/395633c4-f423-44b8-aefa-ef94445c30a9)

# Details

Running default project.

## `package.json`
```package.json
{
  "name": "animotion",
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.2.0",
    "@sveltejs/kit": "^2.5.8",
    "@sveltejs/vite-plugin-svelte": "^3.1.0",
    "@types/reveal.js": "^5.0.3",
    "prettier": "^3.2.5",
    "prettier-plugin-svelte": "^3.2.3",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "shiki": "^1.6.0",
    "shiki-magic-move": "^0.4.2",
    "svelte": "5.0.0-next.167",
    "svelte-check": "^3.7.1",
    "tslib": "^2.6.2",
    "typescript": "^5.4.5",
    "vite": "^5.2.11"
  },
  "dependencies": {
    "@animotion/core": "*",
    "@animotion/motion": "*",
    "@fontsource-variable/jetbrains-mono": "^5.0.21",
    "@fontsource-variable/manrope": "^5.0.20",
    "@tailwindcss/vite": "4.0.0-alpha.14",
    "reveal.js": "^5.1.0",
    "tailwindcss": "4.0.0-alpha.14"
  },
  "trustedDependencies": [
    "svelte-preprocess"
  ]
}
```

## Package Manager

`bun 1.1.20+ae1948925`

## Browser

`Chrome Version 126.0.6478.182 (Official Build) (64-bit)`

## OSes

`Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

`Windows 11 Version 23H2 (OS Build 22631.3880)`

Let mo know if there any additional information you need.

**Comment by mattcroat** [comment]
What is the problem?

**Comment by mattcroat** [comment]
I had a look and I don't know what's causing it but reloading seems to fix the problem until I figure it out.

**Comment by ImBIOS** [comment]
![image](https://github.com/user-attachments/assets/8d5d360a-f7bf-435c-af3b-a6ab6b4b41b9)

Thanks, it's fixed. But, is it not supposed to show all the content in the upcoming preview? Or, is it expected only to show a portion of the content of the next slide?

**Comment by mattcroat** [comment]
Animotion uses [reveal](https://revealjs.com/speaker-view/) for the slides so that's just how it works as far as I know.
