### ISSUE TITLE
How to access other routes by creating a folder in /routes ?

### ISSUE THREAD

**Issue by chauhanvats3** [animotionjs/animotion#34]
I don't wish to initiate a new project for each topic and thus, I though of creating separate routes for those.
I created a route called `/closures` and inside, I created a `+page.svelte` file. 

However, If I enter the route `http://localhost:5137/#/closures` , it would take me to homepage instead. 

Is this how it will be or is there something I can do about it?

**Comment by mattcroat** [comment]
Instead of `http://localhost:5173/#/closures` the URL should be `http://localhost:5173/closures` and it should work.
