### ISSUE TITLE
`focused` doesn't seem to work in v`^1.0.15`

### ISSUE THREAD

**Issue by Blankeos** [animotionjs/animotion#40]
My versions:

```json
"svelte": "5.0.0-next.167",
"@animotion/core": "^1.0.15",
```

I'm running:

```ts
		<Action
			do={() => {
				console.log('do 1')
			}}
			focused={() => {
				console.log('focused 1')
			}}
		/>
		<Action
			do={() => {
				console.log('do 2')
			}}
			focused={() => {
				console.log('focused 2')
			}}
		/>
```

Literally only logs:
<img width="177" alt="image" src="https://github.com/user-attachments/assets/853b984c-1967-494e-862b-a77d42cf2d9f">

Here's a minimal example if you're wondering what other versions I have:
https://github.com/Blankeos/animotion-focused-bug-mre

**Comment by Blankeos** [comment]
Downgraded for now.

**Comment by mattcroat** [comment]
@Blankeos `focused` was a separate prop but the behavior was moved to `do` so it works the same — I don't know how you found it because it was only inside https://github.com/animotionjs/animotion/pull/37 and I forgot to remove it after

**Comment by Blankeos** [comment]
Hi @mattcroat thanks for the quick response.

Sorry but can you answer this question? 
https://github.com/animotionjs/animotion/issues/36#issuecomment-2351811486

I kind of have a usecase for `undo` as well.

Specifically for a custom **visible** state that works with the presentation state.
- When do, visible = true
- When undo, visible = false

---

Do you think this new `do` behavior gives me the option to know when something goes "out of focus"?

**Comment by mattcroat** [comment]
@Blankeos open a new issue with an example
