### ISSUE TITLE
Add Support for Canvas like excalidraw

### ISSUE THREAD

**Issue by jazimabbas** [animotionjs/animotion#41]
@mattcroat Can you please add support for canvas like excalidraw. It would be great if you can add that feature as well.

**Comment by mattcroat** [comment]
can you explain the feature? 😄

**Comment by jazimabbas** [comment]
That's funny 😄. I want to explain my code snippets through arrows or different diagram tools like excalidraw. But I don't want to add all the canvas stuff by myself 😄.  I can code for different slides but I think that will be repetitive task. 
So that's why I was asking it.

**Comment by mattcroat** [comment]
I see but can't you just use the Excalidraw package or `<iframe>` it in your the slide?

**Comment by mattcroat** [comment]
it sucks that [Excalidraw](https://github.com/excalidraw/excalidraw) and [tldraw](https://github.com/tldraw/tldraw) only work with React but there's probably another library that does something similar
