### ISSUE TITLE
Math equations are being y-scaled during transitions 

### ISSUE THREAD

**Issue by ASSimonsen** [animotionjs/animotion#47]
Hi
When adding transitions after a math equation, which has either subscripts or superscripts, the equations are scaled in the y-direction. 

```
<script lang="ts">
	import { Presentation, Slide, Transition } from '@animotion/core'
</script>

<Presentation options={{ history: false, transition: 'slide', controls: false, progress: true }}>
	<Slide class="h-full place-content-center place-items-center">
		<Transition>
			{`\\[ A_1 \\]`}
		</Transition>
		<Transition>
			{`\\[ B \\]`}
		</Transition>
		<Transition>
			{`\\[ C^2 \\]`}
		</Transition>
		<Transition>
			{`\\[ D \\]`}
		</Transition>
		<Transition>
			{`\\[ \\dot{E} \\]`}
		</Transition>
		<Transition>
			{`\\[ F \\]`}
		</Transition>
	</Slide>
</Presentation>
````

The presentation above will render A_1, C^2 and \dot{E} incorrectly during the transitions, where they are squeezed in the y-direction. 

Great work on the tool nevertheless. 

Kind regards Anders

**Comment by mattcroat** [comment]
I looked into it, but I have no idea what's causing it — I should probably remove the math plugin and find something better that also lets you animate the formula.

**Comment by ASSimonsen** [comment]
All right, thanks :)
