### ISSUE TITLE
Feature request: Code block highlighting on init

### ISSUE THREAD

**Issue by isaacharrisholt** [animotionjs/animotion#48]
Hey! Love Animotion, and have started using it for all my YouTube videos.

I'd love to be able to highlight lines `<Code>` element on render, rather than having to call an action myself. Sometimes I want a specific line highlighted when I get to a slide, without the animation playing. I was thinking something like this:

```svelte
<Code
  {...props}
  highlighted="1"
/>
```

It could take the same format as `selectLines` currently does, but just ensure they're highlighted by default.

Thanks!

**Comment by mattcroat** [comment]
I like your idea, but it requires more thought, since it would also make sense that you could highlight tokens — unfortunately, I don't see myself using it, so I lack the motivation, but I might reconsider it.
