### ISSUE TITLE
How to make actions in Speaker View appear in Main View

### ISSUE THREAD

**Issue by TATAPNHOB** [animotionjs/animotion#7]
Hello! Love using this framework so far. One bit of struggle for me compared to Powerpoint is that I mostly use the Presenter/Speaker View for navigating and interacting with the presentation. But, in Animotion, it seems that the Main View window and the Speaker View iframe aren't linked (for example, if there's a div with on:click event and it's clicked in Speaker View, the changes are local to that view only). Is there a way to have changes in Speaker View propagate to the main window too?

**Comment by mattcroat** [comment]
I don't think so, but you can learn everything about the [speaker view](https://revealjs.com/speaker-view/) from the Reveal.js docs and Animotion exposes every component inside `src/lib/components`.
