### ISSUE TITLE
Multiple presentations with the same website

### ISSUE THREAD

**Issue by Kraktoos** [animotionjs/animotion#8]
It would be cool if it were possible to have various presentations within the same website and then some sort of global readable store where that you can use to display info about all presentations in the index page (such as title, etc) and redirect to each one.

**Comment by mattcroat** [comment]
You can have multiple presentations if you enable `embedded` in the configuration which is what I do for the [custom Animotion component](https://github.com/animotionjs/animotion/blob/main/packages/docs/src/lib/animotion/animotion.svelte) for the docs.
