### ISSUE TITLE
Right-to-Left (RTL) Support

### ISSUE THREAD

**Issue by HJassar** [animotionjs/animotion#9]
Right-to-left support means that:

- the navigation controls will float on the left
- the horizontal slide goes from left to right
- progress will fill from right to left.

**Comment by mattcroat** [comment]
@HJassar You can already change the presentation direction: https://revealjs.com/config/.

**Comment by HJassar** [comment]
Thank you. There are a couple of issues, however;
1. The controls' only allowed positioning (besides edges) is bottom-right.
2. In RTL mode, the left and right arrows go to the next slide.

**Comment by mattcroat** [comment]
That's not something I have control over since I use Reveal.js as the base but maybe you could make a [plugin](https://revealjs.com/plugins/) that modifies the presentation the way you want.

**Comment by HJassar** [comment]
Thank you.
